exclude = [ '.*\.nip.io', '.*support.cloudbees.com.*', '.*example:8080.*', '.*fhir-pseudonymizer:8080.*', '^https://github.com/miracum/recruit/compare/' ]
exclude_path = [ 'src/list/frontend/public/index.html' ]
exclude_all_private = true
