site_name: recruIT
site_url: https://miracum.github.io/recruit/
site_description: >-
  A Cloud-Native Clinical Trial Recruitment Support System based on HL7 FHIR and the OMOP CDM.

repo_name: miracum/recruit
repo_url: https://github.com/miracum/recruit
edit_uri: ""

copyright: Copyright &copy; 2023 miracum.org

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - pymdownx.snippets:
      base_path:
        - "docs"
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.miracum.org/
      name: MIRACUM Website
extra_css:
  - _css/extra.css
theme:
  name: material
  logo: _img/miracum-logo-transparent-256x256.png
  favicon: _img/favicon.ico
  features:
    - navigation.expand
    - navigation.sections
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
